name: Build and Publish image to Docker Hub

on:
  push:
    branches: [ "main" ]
    paths:
     - 'Dockerfile'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag opscentre/firebird-ubuntu-chiselled:latest
    - name: Push image to Docker Hub
      run: |
        docker login -u opscentre -p ${{secrets.DOCKER_HUB_TOKEN}}
        docker push opscentre/firebird-ubuntu-chiselled:latest
